apiVersion: v2
name: muthur
description: AI-powered Kubernetes monitoring central agent
type: application
version: 0.1.5
appVersion: "0.1.4"
kubeVersion: ">=1.24.0-0"
icon: https://assets.pastyrik.dev/images/muthur-icon.png
home: https://github.com/VojtechPastyrik/muthur
sources:
  - https://github.com/VojtechPastyrik/muthur
maintainers:
  - name: Vojtech Pastyrik
    email: vojtech@pastyrik.dev
    url: https://pastyrik.dev
keywords:
  - monitoring
  - kubernetes
  - alerting
  - ai
  - claude
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/prerelease: "false"
  artifacthub.io/maintainers: |
    - name: Vojtech Pastyrik
      email: vojtech@pastyrik.dev
