apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "muthur-central.fullname" . }}-config
  labels:
    {{- include "muthur-central.labels" . | nindent 4 }}
data:
  routing.yaml: |
    rules:
    {{- range .Values.routing.rules }}
      - name: {{ .name | quote }}
        match:
          {{- if .match.severity }}
          severity: {{ .match.severity | quote }}
          {{- end }}
          {{- if .match.cluster_id }}
          cluster_id: {{ .match.cluster_id | quote }}
          {{- end }}
          {{- if .match.alert_name }}
          alert_name: {{ .match.alert_name | quote }}
          {{- end }}
          {{- if .match.namespace }}
          namespace: {{ .match.namespace | quote }}
          {{- end }}
        notify:
        {{- range .notify }}
          - {{ . | quote }}
        {{- end }}
        {{- if not .notify }}
          []
        {{- end }}
    {{- end }}
